spring:
  application:
    name: apollo-portal
  profiles:
    active: ${apollo_profile:local}
  jpa:
    properties:
      hibernate:
        query:
          plan_cache_max_size: 192 # limit query plan cache max size
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
  port: ${server_port:8071}
  compression:
    enabled: true
  tomcat:
    use-relative-redirects: true

logging:
  file: ${log_path:/data/log/apollo-portal.log}

management:
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP



